### ISSUE TITLE
mscorlib error when trying to dump

### ISSUE THREAD

**Issue by mrjamiebowman** [ycherkes/ObjectDumper#41]
Visual Studio 2022 Enterprise
.NET 6

Can't get this to do anything... it opens a new window objectname.cs and has this error message.

"error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'."

mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**Comment by ycherkes** [comment]
@mrjamiebowman I need more info from you to reproduce this issue.
Could you please run the following code in your **Immediate Window** and give me the output?
`typeof(System.String).Assembly.Location`
My assumption: the extension injects something different than the net6.0 targeted library.

**Comment by gvdmaaden** [comment]
I'm having the same issue. I'm debugging a azure function locally and got the same message. When I excecute the typeof method that you mentioned in the immediate window it got this: 
typeof(System.String).Assembly.Location
"C:\\User\\User\\AppData\\Local\\AzureFunctionsTools\\Releases\\4.30.0\\cli_x64\\System.Private.CoreLib.dll"

**Comment by ycherkes** [comment]
@gvdmaaden Many thanks - will take a look.

**Comment by ycherkes** [comment]
@gvdmaaden Could you please update the extension to v 0.0.0.72 and check if it works properly?

**Comment by gvdmaaden** [comment]
@ycherkes That did the trick,! It works again, thank you very much. Your Objectdumper is a real help, especially when making mocks for unit testing! Keep up the good work!

**Comment by ycherkes** [comment]
Thank you for the kind words, closing the issue.

**Comment by ycherkes** [comment]
Fixed in v 0.0.0.72
