### ISSUE TITLE
Error shown for anything I try and use

### ISSUE THREAD

**Issue by sabasjon** [ycherkes/ObjectDumper#49]
Hi There

We just installed this extension (v0.0.0.75) but unable to get it to work.  

We are using VS 2022 Version 17.4.4 and when we are at a breakpoint and right click on any variable and select Dump As  'x' then we are presented with a new document window and at the top the following error message is displayed

error CS1503: Argument 1: cannot convert from 'string' to 'char'

We tried to dump on simple numbers, strings etc - with lines of code such as

var i = 0;
var something = "Hello World";
var lstStr = new List<string> { "hello", "there" };

but everything just returns this CS1503 error.  We tried on dumping to c#, JSON, XML etc

Are we doing something wrong?

**Comment by ycherkes** [comment]
Hi @sabasjon 
~~I need more details:~~
 ~~- is project language C#?~~
 ~~- .NetFramework or .NetCore, version?~~
 ~~- is Visual Studio locale en-us?~~

**Comment by ycherkes** [comment]
I've reproduced an issue - .NetFramework support was broken.
Could you please download last version of this extension ([v.0.0.0.76](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/YevhenCherkes/vsextensions/YellowFlavorObjectDumper/0.0.0.76/vspackage))  from marketplace, check it out and let me know if issue has gone?

**Comment by ycherkes** [comment]
I just checked out - .NetFramework support was broken - so it should work now.

**Comment by sabasjon** [comment]
Hi There

Thanks so much for the quick response on this - I have just updated to 0.0.0.76 and can confirm all working for us now.

Cheers

**Comment by ycherkes** [comment]
@sabasjon thank you for opening this issue. 
Fixed in v0.0.0.76
