### ISSUE TITLE
UnauthorizedAccessException on YellowFlavor.Serialization.dll

### ISSUE THREAD

**Issue by salem-mdimegh** [ycherkes/ObjectDumper#90]
Using Microsoft Visual Studio Enterprise 2022 (64-bit) 
Version 17.9.6

Every time when I try to "Dump as" to any type.
Exception : 

> 'System.Reflection.Assembly.LoadFile(@"c:\users\xxxxxxxxx\appdata\local\microsoft\visualstudio\17.0_607f993c\extensions\lzbpc2iq.5i1\InjectableLibs\net45\YellowFlavor.Serialization.dll")' threw an exception of type 'System.UnauthorizedAccessException'

**Comment by ycherkes** [comment]
I need more details. Windows version, dotnet version?

**Comment by ycherkes** [comment]
@salem-mdimegh Thank you for reporting this issue.
Could you paste it to code you debugging and check what happens?

```
 using System;
 using System.Security.Permissions;
 using System.Security;


var f1 = new FileIOPermission(FileIOPermissionAccess.Read, @"c:\users\xxxxxxxxx\appdata\local\microsoft\visualstudio\17.0_607f993c\extensions\lzbpc2iq.5i1\InjectableLibs\net45\YellowFlavor.Serialization.dll");
try
{
    f1.Demand();
}
catch (SecurityException s)
{
    Console.WriteLine(s.Message);
}
```

**Comment by ycherkes** [comment]
Also, the information about the OS and .net framework version will be very helpful.

**Comment by ycherkes** [comment]
I can't reproduce, so, just waiting for the input from reporter.

**Comment by ycherkes** [comment]
Same bug was reported by Troy Loberger 10.04.23 in QA. netframework version of serialization library couldn't be loaded with the same exception.

> I'm getting an authorization exception. I'm running VS as an administrator. Any thoughts?

> 'System.Reflection.Assembly.LoadFile(@"c:\users\MyName\appdata\local\microsoft\visualstudio\17.0_bc416d50\extensions\yt4v04nk.33h\InjectableLibs\net45\YellowFlavor.Serialization.dll")' threw an exception of type 'System.UnauthorizedAccessException'

**Comment by salem-mdimegh** [comment]
OS : Windows 10 Entreprise 22H2
Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz   2.90 GHz
16,0 Go RAM

Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.9.6 
ASP.NET MVC app
Target Framework : .NET Framework 4.7.2

the code given on prevous comment [here](https://github.com/ycherkes/ObjectDumper/issues/90#issuecomment-2135355111), did not raise exception
![image](https://github.com/ycherkes/ObjectDumper/assets/23358813/92f072db-0faa-46ee-bce2-e9088070bac9)

**Comment by ycherkes** [comment]
@salem-mdimegh 
Could you please also run?

`var assembly = System.Reflection.Assembly.LoadFile(@"c:\users\xxxxxxxxx\appdata\local\microsoft\visualstudio\17.0_607f993c\extensions\lzbpc2iq.5i1\InjectableLibs\net45\YellowFlavor.Serialization.dll");`

**Comment by ycherkes** [comment]
Or even better this code. I will know if it can be used as a workaround:

```
var fileData = System.IO.File.ReadAllBytes(@"c:\users\xxxxxxxxx\appdata\local\microsoft\visualstudio\17.0_607f993c\extensions\lzbpc2iq.5i1\InjectableLibs\net45\YellowFlavor.Serialization.dll");
var base64String = Convert.ToBase64String(fileData);
var asm = System.Reflection.Assembly.Load(System.Convert.FromBase64String(base64String));
```

**Comment by ycherkes** [comment]
That could be related to [CAS policy](https://www.codemag.com/article/0405031/Managing-.NET-Code-Access-Security-CAS-Policy)

`caspol -all -lg`

Try adding this library to fully trusted in the developer command prompt console under Administrator:

`caspol -m -ag 1.2 -url "file:///c:/users/xxxxxxxxx/appdata/local/microsoft/visualstudio/17.0_607f993c/extensions/lzbpc2iq.5i1/InjectableLibs/net45/YellowFlavor.Serialization.dll" FullTrust`

**Comment by furoTmark-ll** [comment]
Hey, I added this to the caspol, but I still receive the same error; however, if I try a dump while running a test, it works. It doesn't work when I run the actual code in debug mode.

**Comment by furoTmark** [comment]
Hey, I added this to the caspol, but I still receive the same error; however, if I try a dump while running a test, it works. It doesn't work when I run the actual code in debug mode.

**Comment by ycherkes** [comment]
@furoTmark Is it run in IIS? If so, could you give IUSR read acces to folder with YellowFlavor.Serialization.dll?

**Comment by furoTmark** [comment]
@ycherkes  it is. 
Added IUSR to file, then to folder, with read then full control, but still get the error.

**Comment by ycherkes** [comment]
@furoTmark 

Please add the following access for  **YourComputerName\IIS_IUSRS** group

**Read-Write** access to %userprofile%\AppData\Local\Temp directory
**Read** access to %userprofile%\AppData\Local\Microsoft\VisualStudio\17.0_607f993c\extensions\lzbpc2iq.5i1\InjectableLibs (or even better to %userprofile%\AppData\Local\Microsoft\VisualStudio) directory

PS:
[ProcMon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) helped me to figure out which account is trying to access the file.

**Comment by ycherkes** [comment]
@furoTmark Feel free to reopen this issue if it persists after the steps above.

**Comment by furoTmark** [comment]
Thanks for the help @ycherkes, I just got to try it out. 
Your suggestions worked!

**Comment by ycherkes** [comment]
You are welcome @furoTmark. Happy coding!
